### ISSUE TITLE
MIPI screen not working on kitra520

### ISSUE THREAD

**Issue by curcuz** [balena-os/meta-artik#26]
The kitra520 supports 2-lane MIPI displays. The reference device supported is `PITEK PA320320A` ( see [this link](https://github.com/rushup/Kitra520/tree/master/Kernel%20release/artik_os_1.1.0) and [this demo](https://youtu.be/sRwMAB-J-DM) ).

When I try to use that screen under ResinOS (tested on 2.0.8+), no fb device is offered and I see this in the logs:

```
[    1.465014] parse_display_driver_dt: decon_driver.regs 11c00000 dsi_driver.regs 11c80000
[    1.465085] samsung,max_bpp: no property in the node, fb_variant.
[    1.465251] parsing fimd platdata is failed.
[    1.465412] parsing DT for fimd controller is failed.
[    1.465553] device tree parse error system
[    1.465682] s5p-decon-display: probe of 11c00000.fimd_fb failed with error -22
```

**Comment by floion** [comment]
We no longer support the kitra lineup
